---
- name: install node and npm
  hosts: aws
  tasks:
    - name: update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm
    
- name: Deploy nodejs app
  hosts: aws
  vars_files:
    - vars.yaml
  tasks:
    - name: unpack nodejs file
      unarchive:
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        dest: "{{destination}}"
    - name: install dependencies
      npm:
        path: "{{destination}}/package"
    - name: start application
      command:
        chdir: "{{destination}}/package/app"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}


