---
plugin: aws_ec2
regions:
  - ca-central-1
filters:
  tag:Name: dev-server-*
  instance-state-name: running
# keyed_groups:
#   - key: tags
#     prefix: tag
#   - key: instance_type
#     prefix: instance_type

