variable "vpc_cidr" {}
variable "subnet_cidr" {}
variable "availability_zone" {}
variable "env_prefix" {}
variable "region" {}
variable "my_ip" {}
variable "instance_type" {}
variable "public_key_location" {}
variable "private_key_location" {}