apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-two
  labels:
    app: myapp-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-two
  template:
    metadata:
      labels:
        app: myapp-two
    spec:
      imagePullSecrets:
      - name: my-registry-key-two
      containers:
      - name: myapp-two
        image: 137236605350.dkr.ecr.ca-central-1.amazonaws.com/my-app:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
